server:
  port: 8080  # ??????????
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/kindle_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update     # ?????create / update / validate?
    show-sql: true         # ????? SQL
    properties:
      hibernate:
        format_sql: true   # ??? SQL ??
  mail:
    host: smtp.qq.com
    port: 587
    username: 3119717318@qq.com
    password: luscaczpesrzdeji
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# ?????????????? uploads ????
file:
  upload-dir: uploads/
  ebook-dir: uploads/ebook/
  cover-dir: uploads/cover/



